version: 0.0
os: linux
files:
  - source: dist/appTareas/browser
    destination: /var/www/html  #la ruta donde alojas tu frontend en EC2

hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 180
      runas: ec2-user
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 180
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 180
      runas: ec2-user
